### ISSUE TITLE
Remove "Don't Miss" tag from History is What's Happening

### ISSUE THREAD

**Issue by clappsam** [san3091/catalytic-soundstream#58]
Remove "Don't Miss" tag from History is What's Happening

This is not a rotating selection, and will be swapped out in full every month.

<img width="215" alt="Screen Shot 2020-07-24 at 11 16 43 AM" src="https://user-images.githubusercontent.com/35810120/88412471-40dde700-cd9f-11ea-86fa-8ef7f375afa0.png">

**Comment by OppNHeimer** [comment]
merged fix into staging
