### ISSUE TITLE
DESIGN REVISIONS 11 SEPTEMBER

### ISSUE THREAD

**Issue by clappsam** [san3091/catalytic-soundstream#74]
Hi Max! Sorry that this is taking so long. We are juggling many things, as always, including now sorting out how to manage the label tier. \

My only question is, could you estimate how long it would take (/would it be feasible) to create a "popout" player so that listeners can browse other items while the selected item still plays.

Anyway, here are a few design revisions from Fede. Almost there.
- Need a bit less space between sections. With the distance they have now, it feels too separated from each other.
- The highlight of the CAA albums is cool but i would not use a "frame" on the sides. I would try without them, just a plain band of color. 
- To my eye, i think the font is now slightly big, and that creates an unbalanced look of the whole site, i think if we go down a point on the font for the album titles/artist AND use a softer grey, rather than the current black, this will help to calm down the black on all the fonts we're using.
- I think the shadow of the first album should be grey or more grey. Right now the black color is too strong and confusing with the cover elements. If not grey, it could be the same red we're using. This could indicate the NEW ITEM instead of having the NEW TODAY sign below (which I think does not look so good and requires there to me more space in between sections.) Using the color is a clear indicator of a new item instead of saying it. 
- The "don't miss" button feels confusing from the design point of view. Can we try another way to feature an album like that? Since none of the other sections have a button like this.
- The space between lines at the STREAM message and the album description is too sparse. If we adjust that the whole chunk of text will be more unified and clear in between the rest of the titles and other texts.

**Comment by OppNHeimer** [comment]
Made a PR that changes:
- reduces spacing between sections
- change the highlighted section background to be full bleed
- reduces the font size of the album title and artist under each cover artwork
- softens the black to be a dark grey for both text and album shadow
- reduce the line-height for paragraph text in mission statement and album description
- reduce the size of 'NEW TODAY' and 'DONT MISS' labels
- restyle 'DONT MISS' button to be less visually intrusive

I think it would take ~10hrs to redesign a solution for users to be able to browse albums while listening. I think we should discuss first as there are likely some limitations around the soundcloud player and I want to make sure they wont conflict with expectations.

**Comment by clappsam** [comment]
Cool, thanks so much. I will run these changes by Fede & Ken and provide further feedback. Could we talk on the phone this week sometime to discuss the popout player?
