### ISSUE TITLE
Bug: History and Catalytic Radio Rotation Not Working

### ISSUE THREAD

**Issue by clappsam** [san3091/catalytic-soundstream#92]
**Describe the bug**
The last CSVs I sent to Santiago were I sent in an email with the subject "2-15 Soundstream Update"

**Catalytic Radio: Sorry I don't have exact details on what is going wrong here. The CSV upload pre-2-15 ended with Paul Lytton & Ken Vandermark's English Suites. For the 2-15 upload, I included 30 albums to populate the first days' rotation and then 15 more for the subsequent 15 days. I believe what happened is that the CSV uploader somehow retained some data from the previous entry, because I remember the newest item being something from a previous upload, about 14 days before the first entry in the 2-15 CSV. Assuming that the rotation would continue though my updated CSV, I left it alone, as no one was complaining and it bought us some extra time.**

**Just a few days ago, it should have passed into the new material in the 2-15 CSV. But instead, it looped back from Paul Lytton & Ken Vandermark's English Suites to Live At The South Bank, and continued from there (that's the first entry in the 2-15 CSV).**

Label Radio: I think this is working correctly. BUT, we should check, because this CSV was not actually updated on 2-15--I simply reuploaded a short version of the CSV from March

Catalytic Artist Albums: This updated correctly. The CSV included all CAAs to date, and they are all there, with no redundancy.

**History Is What's Happening: The 2-15 CSV upload contained 10 albums that were supposed to replace the previous 10. Instead, there are now 20 albums.**

**Comment by djbroccoli** [comment]
Issue resolved. Replaced stream with new CSVs on 4/2/2021. Hopefully we will have an admin panel by the time of the next import!

**Comment by san3091** [comment]
Thanks for closing this! 👏🏼
